before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=1
  - goos:
      - linux
      - windows
      - darwin
    main: ./cmd
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
