before:
  hooks:
    - go mod tidy
builds:
  - id: linux
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    main: ./cmd
    ldflags:
      - -linkmode external -extldflags '-static' -s -w
  - id: non-linux
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
    main: ./cmd
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
